package com.shinowit.dao.mapper;

import com.shinowit.entity.Clerk;
import com.shinowit.entity.ClerkExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ClerkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int countByExample(ClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int deleteByExample(ClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int insert(Clerk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int insertSelective(Clerk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    List<Clerk> selectByExample(ClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    Clerk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Clerk record, @Param("example") ClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByExample(@Param("record") Clerk record, @Param("example") ClerkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByPrimaryKeySelective(Clerk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByPrimaryKey(Clerk record);
}