package com.shinowit.dao.mapper;

import com.shinowit.entity.ClerkAddress;
import com.shinowit.entity.ClerkAddressExample;
import com.shinowit.entity.ClerkAddressKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ClerkAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int countByExample(ClerkAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int deleteByExample(ClerkAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int deleteByPrimaryKey(ClerkAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int insert(ClerkAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int insertSelective(ClerkAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    List<ClerkAddress> selectByExample(ClerkAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    ClerkAddress selectByPrimaryKey(ClerkAddressKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClerkAddress record, @Param("example") ClerkAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByExample(@Param("record") ClerkAddress record, @Param("example") ClerkAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByPrimaryKeySelective(ClerkAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    int updateByPrimaryKey(ClerkAddress record);
}