package com.shinowit.dao.mapper;

import com.shinowit.entity.StuInfo;
import com.shinowit.entity.StuInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int countByExample(StuInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int deleteByExample(StuInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int deleteByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int insert(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int insertSelective(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    List<StuInfo> selectByExample(StuInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    StuInfo selectByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") StuInfo record, @Param("example") StuInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int updateByExample(@Param("record") StuInfo record, @Param("example") StuInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int updateByPrimaryKeySelective(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 12:15:19 CST 2014
     */
    int updateByPrimaryKey(StuInfo record);
}