package com.shinowit.entity;

import java.io.Serializable;

public class ClerkAddressKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clerk_address.house_no
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private Integer houseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clerk_address.street_no
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private Integer streetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clerk_address.house_no
     *
     * @return the value of clerk_address.house_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public Integer getHouseNo() {
        return houseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clerk_address.house_no
     *
     * @param houseNo the value for clerk_address.house_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public void setHouseNo(Integer houseNo) {
        this.houseNo = houseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clerk_address.street_no
     *
     * @return the value of clerk_address.street_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public Integer getStreetNo() {
        return streetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clerk_address.street_no
     *
     * @param streetNo the value for clerk_address.street_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public void setStreetNo(Integer streetNo) {
        this.streetNo = streetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClerkAddressKey other = (ClerkAddressKey) that;
        return (this.getHouseNo() == null ? other.getHouseNo() == null : this.getHouseNo().equals(other.getHouseNo()))
                && (this.getStreetNo() == null ? other.getStreetNo() == null : this.getStreetNo().equals(other.getStreetNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk_address
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHouseNo() == null) ? 0 : getHouseNo().hashCode());
        result = prime * result + ((getStreetNo() == null) ? 0 : getStreetNo().hashCode());
        return result;
    }
}