package com.shinowit.entity;

import java.io.Serializable;

public class Clerk implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clerk.id
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clerk.name
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clerk.street_no
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private Integer streetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clerk.house_no
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private Integer houseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clerk.id
     *
     * @return the value of clerk.id
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clerk.id
     *
     * @param id the value for clerk.id
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clerk.name
     *
     * @return the value of clerk.name
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clerk.name
     *
     * @param name the value for clerk.name
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clerk.street_no
     *
     * @return the value of clerk.street_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public Integer getStreetNo() {
        return streetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clerk.street_no
     *
     * @param streetNo the value for clerk.street_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public void setStreetNo(Integer streetNo) {
        this.streetNo = streetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clerk.house_no
     *
     * @return the value of clerk.house_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public Integer getHouseNo() {
        return houseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clerk.house_no
     *
     * @param houseNo the value for clerk.house_no
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    public void setHouseNo(Integer houseNo) {
        this.houseNo = houseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Clerk other = (Clerk) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getStreetNo() == null ? other.getStreetNo() == null : this.getStreetNo().equals(other.getStreetNo()))
                && (this.getHouseNo() == null ? other.getHouseNo() == null : this.getHouseNo().equals(other.getHouseNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clerk
     *
     * @mbggenerated Mon Sep 05 11:22:41 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getStreetNo() == null) ? 0 : getStreetNo().hashCode());
        result = prime * result + ((getHouseNo() == null) ? 0 : getHouseNo().hashCode());
        return result;
    }
}