package com.shinowit.entity;

import java.io.Serializable;

public class StuInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.stu_id
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.stu_name
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.stu_pass
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    private String stuPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.stu_sex
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    private String stuSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.stu_id
     *
     * @return the value of stu_info.stu_id
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.stu_id
     *
     * @param stuId the value for stu_info.stu_id
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.stu_name
     *
     * @return the value of stu_info.stu_name
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.stu_name
     *
     * @param stuName the value for stu_info.stu_name
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.stu_pass
     *
     * @return the value of stu_info.stu_pass
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public String getStuPass() {
        return stuPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.stu_pass
     *
     * @param stuPass the value for stu_info.stu_pass
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public void setStuPass(String stuPass) {
        this.stuPass = stuPass == null ? null : stuPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.stu_sex
     *
     * @return the value of stu_info.stu_sex
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.stu_sex
     *
     * @param stuSex the value for stu_info.stu_sex
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex == null ? null : stuSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StuInfo other = (StuInfo) that;
        return (this.getStuId() == null ? other.getStuId() == null : this.getStuId().equals(other.getStuId()))
            && (this.getStuName() == null ? other.getStuName() == null : this.getStuName().equals(other.getStuName()))
            && (this.getStuPass() == null ? other.getStuPass() == null : this.getStuPass().equals(other.getStuPass()))
            && (this.getStuSex() == null ? other.getStuSex() == null : this.getStuSex().equals(other.getStuSex()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 21:08:23 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStuId() == null) ? 0 : getStuId().hashCode());
        result = prime * result + ((getStuName() == null) ? 0 : getStuName().hashCode());
        result = prime * result + ((getStuPass() == null) ? 0 : getStuPass().hashCode());
        result = prime * result + ((getStuSex() == null) ? 0 : getStuSex().hashCode());
        return result;
    }
}